# Generated by Django 5.0.6 on 2024-07-14 15:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObjectStorageLogModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deleted_by", models.CharField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("bucket", models.CharField()),
                ("key", models.CharField(db_index=True, unique=True)),
                ("name", models.CharField()),
                ("description", models.CharField()),
                ("content_type", models.CharField()),
                ("meta_data", models.JSONField()),
            ],
            options={
                "db_table": "object_storage_logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailTemplateModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deleted_by", models.CharField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(db_index=True)),
                ("placeholders", models.JSONField()),
                ("file_sys_path", models.CharField(db_index=True)),
                (
                    "object_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="template.objectstoragelogmodel",
                    ),
                ),
            ],
            options={
                "db_table": "mail_templates",
                "ordering": ["created_at"],
            },
        ),
    ]
