# Generated by Django 5.0.6 on 2024-07-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectstoragelogmodel",
            name="meta_data",
            field=models.JSONField(null=True),
        ),
    ]
