# Generated by Django 5.0.6 on 2024-07-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0002_alter_objectstoragelogmodel_meta_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailtemplatemodel",
            name="placeholders",
            field=models.JSONField(null=True),
        ),
    ]
