# Generated by Django 5.0.6 on 2024-07-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0003_alter_mailtemplatemodel_placeholders"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplatemodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="objectstoragelogmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
