# Generated by Django 5.1 on 2024-08-23 12:17

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0004_mailtemplatemodel_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplatemodel",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(
                    access_key="R4DIMjo26wKM4BaKIyBY",
                    bucket_name="nova",
                    endpoint_url="http://localhost:9000",
                    secret_key="glMxKmEWoMOsZgelLHp330lUu2VasCwbLUM0EJxJ",
                ),
                upload_to="",
            ),
        ),
    ]
