# Generated by Django 5.1 on 2024-08-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0005_mailtemplatemodel_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailtemplatemodel",
            name="object_storage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="template.objectstoragelogmodel",
            ),
        ),
    ]
