# Generated by Django 5.1 on 2024-08-23 12:46

import django.core.validators
import storages.backends.s3
from django.db import migrations, models

import core.utils.util


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0007_remove_mailtemplatemodel_object_storage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailtemplatemodel",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(
                    access_key="R4DIMjo26wKM4BaKIyBY",
                    bucket_name="nova",
                    endpoint_url="http://localhost:9000",
                    secret_key="glMxKmEWoMOsZgelLHp330lUu2VasCwbLUM0EJxJ",
                ),
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3"]
                    ),
                    core.utils.util.validate_file_size,
                ],
            ),
        ),
    ]
