# Generated by Django 5.1 on 2024-08-23 15:01

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0008_alter_mailtemplatemodel_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplatemodel",
            name="file_system_id",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="mailtemplatemodel",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(
                    access_key="R4DIMjo26wKM4BaKIyBY",
                    bucket_name="nova",
                    endpoint_url="http://127.0.0.1:9000",
                    secret_key="glMxKmEWoMOsZgelLHp330lUu2VasCwbLUM0EJxJ",
                    signature_version="s3v4",
                ),
                upload_to="",
            ),
        ),
    ]
