version: "3.8"
services:
  email_backend:
    image: drf-be-email-service:latest
    container_name: "drf-email-backend"
    env_file:
      - .env
    ports:
      - "8001:8000"
    networks:
      - drf_notification_service
    depends_on:
      email_migration:
        condition: service_completed_successfully
      email_redis:
        condition: service_healthy
      email_celery_worker:
        condition: service_started
      minio:
        condition: service_started

  email_migration:
    image: drf-be-email-service:latest
    container_name: "drf-email-migration"
    command: python manage.py migrate
    env_file:
      - .env
    networks:
      - drf_notification_service
    depends_on:
      email_backend_db:
        condition: service_healthy

  email_backend_db:
    image: postgres:16
    container_name: "drf-email-backend-db"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ~/temp/docker-volumes/drf-email-database:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - drf_notification_service
    healthcheck:
        test: ["CMD", "pg_isready",  "-U", "${DB_USER}", "-d", "${DB_NAME}"]

  email_redis:
    image: redis:6.2.6-alpine
    container_name: "drf-email-redis"
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6377:6379"
    networks:
      - drf_notification_service
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]

  email_celery_worker:
    image: drf-be-email-service:latest
    container_name: "drf-email-celery-worker"
    env_file:
      - .env
    command: celery -A config worker -l INFO --pool=threads --concurrency=5
    networks:
      - drf_notification_service
    depends_on:
      email_backend_db:
        condition: service_healthy
      email_redis:
        condition: service_healthy

  minio:
    image: quay.io/minio/minio
    container_name: "minio-server"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: p@ssw0rd
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/temp/docker-volumes/minio-storage:/data
    networks:
      - drf_notification_service

networks:
  drf_notification_service:
    name: drf_notification_network
