# Generated by Django 5.0.6 on 2024-07-14 12:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SingleMailModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("sender", models.CharField(db_index=True)),
                ("name", models.CharField(db_index=True)),
                ("recipient", models.CharField(db_index=True)),
                ("subject", models.CharField()),
                ("html_body", models.CharField()),
                ("text_body", models.CharField()),
                ("is_scheduled", models.BooleanField(default=False)),
                ("scheduled_date", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deleted_by", models.CharField(null=True)),
            ],
            options={
                "db_table": "single_mails",
                "ordering": ["created_at"],
            },
        ),
    ]
