# Generated by Django 5.0.6 on 2024-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("single", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="singlemailmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
