# Generated by Django 5.1 on 2024-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("single", "0002_singlemailmodel_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlemailmodel",
            name="text_body",
            field=models.CharField(null=True),
        ),
    ]
