# Generated by Django 5.0.6 on 2024-07-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maildeliverymodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
