# Generated by Django 5.0.6 on 2024-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0002_maildeliverymodel_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maildeliverymodel",
            name="total_recipients",
            field=models.IntegerField(default=0),
        ),
    ]
