# Generated by Django 5.0.6 on 2024-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0003_alter_maildeliverymodel_total_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maildeliverymodel",
            name="comment",
            field=models.JSONField(null=True),
        ),
    ]
