# Generated by Django 5.0.6 on 2024-07-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk", "0001_initial"),
        ("delivery", "0004_alter_maildeliverymodel_comment"),
        ("single", "0002_singlemailmodel_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maildeliverymodel",
            name="bulk_mail_id",
        ),
        migrations.RemoveField(
            model_name="maildeliverymodel",
            name="single_mail_id",
        ),
        migrations.AddField(
            model_name="maildeliverymodel",
            name="bulk_mail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bulk.bulkmailmodel",
            ),
        ),
        migrations.AddField(
            model_name="maildeliverymodel",
            name="single_mail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="single.singlemailmodel",
            ),
        ),
    ]
