# Generated by Django 5.0.6 on 2024-07-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk", "0002_remove_bulkmailmodel__group_ids"),
        ("delivery", "0005_remove_maildeliverymodel_bulk_mail_id_and_more"),
        ("single", "0002_singlemailmodel_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maildeliverymodel",
            name="bulk_mail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bulk.bulkmailmodel",
            ),
        ),
        migrations.AlterField(
            model_name="maildeliverymodel",
            name="provider",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="maildeliverymodel",
            name="single_mail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery",
                to="single.singlemailmodel",
            ),
        ),
    ]
