# Generated by Django 5.0.6 on 2024-07-24 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk", "0002_remove_bulkmailmodel__group_ids"),
        ("delivery", "0006_alter_maildeliverymodel_bulk_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maildeliverymodel",
            name="bulk_mail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery",
                to="bulk.bulkmailmodel",
            ),
        ),
    ]
