# Generated by Django 5.1 on 2024-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk", "0002_remove_bulkmailmodel__group_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkmailmodel",
            name="text_body",
            field=models.CharField(null=True),
        ),
    ]
